import { GeistSans } from 'geist/font/sans';
import "./globals.css";
import { auth } from "./api/auth/[...nextauth]/route";
import { SessionProvider } from "next-auth/react";
import { CartProvider } from "@/context/CartContext";

export const metadata = {
  title: "Hub Market",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();
  return (
    <html lang="en" className={GeistSans.className}>
      <body>
        <SessionProvider session={session}>
          <CartProvider>
            {children}
          </CartProvider>
        </SessionProvider>
      </body>
    </html>
  );
}